### ISSUE TITLE
Sending a message doesn't allow for "system" or custom types

### ISSUE THREAD

**Issue by kainosnoema** [GetStream/stream-chat-go#104]
Looks like the request to send a message doesn't include the `Type` field: https://github.com/GetStream/stream-chat-go/blob/v3.0.0/message.go#L76-L84

gz#6674

**Comment by shodgetts** [comment]
Agent comment from ferhat elmas in <a href='https://getstream.zendesk.com/agent/tickets/6674'>Zendesk ticket #6674</a>:<br><br>This is a readonly field which client shouldn't write.
However, it's used by server to acknowledge to clients such as pre-send hook prevented message to be sent.

For system messages, set silent property to true.

**Comment by ferhatelmas** [comment]
There is no custom type, but you can set custom fields on your message as you want.

**Comment by kainosnoema** [comment]
Got it... ok. The docs mention that “The type of the message is set by the APIs or by chat bots and custom commands.” so I assumed it could be set by the server clients.

Seems like if I want to send system-style messages, such as what the React components do for messages of type “system”, I’ll need to reimplement the UI then....

**Comment by ferhatelmas** [comment]
You need to set silent to true for similar behavior while sending. You can read `message.Type` to customize your UI then.
