### ISSUE TITLE
Determine Channel ID

### ISSUE THREAD

**Issue by hz081** [GetStream/stream-chat-go#118]
I just notice that in the other language the Channel ID is optional. But in this library, it's mandatory. So now I got duplicate channel, which one generated by the backend and the other one is generated by the front end.

I think this is the issue about the consistency. While other language allow it to be null, but in Go the Channel ID is mandatory.

Could you please solve this inconsistency issue? 

gz#11081

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/11081'>Zendesk ticket #11081</a>:<br><br>Hi,

Thanks for reaching out! We'll look into this and get back to you as soon as possible.

Best,
Ryan

**Comment by ferhatelmas** [comment]
@hz081 Channel ID isn't required if you provide members. Could you provide a code snippet so that I can help what might be wrong there?

**Comment by ferhatelmas** [comment]
@hz081 will close this ticket since I don't see any issues but let me know if you need any further help.
