### ISSUE TITLE
Proposal: integrate golangci-lint to automate quality checks

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-chat-go#12]
If decided, happy to take care it.

**Comment by tbarbugli** [comment]
never used; I kind of like review-dog + metalinter, needs some tweaks to reduce noise but eventually you get nice PR review comments for free

**Comment by ferhatelmas** [comment]
@tbarbugli pushed a PR that does main integration, and corrected issues from errcheck. For the rest, I will wait for your confirmation.

**Comment by Bogdan-D** [comment]
metalinter is dead, golang-ci is better replacement. We'll add it soon

**Comment by ferhatelmas** [comment]
@Bogdan-D see https://github.com/GetStream/stream-chat-go/pull/14 - waiting for review.
