### ISSUE TITLE
DataTemplate field missing in FirebaseConfig?

### ISSUE THREAD

**Issue by fr3fou** [GetStream/stream-chat-go#134]
![image](https://user-images.githubusercontent.com/1344906/129916125-0e09d1f9-ddbd-4942-b56f-9150e394af7b.png)
Docs show that there should be a `data_template` field, but there isn't one
![image](https://user-images.githubusercontent.com/1344906/129916154-6f9c9c85-78f5-473a-a68a-9cbdd8885deb.png)

**Comment by streamiosupport** [comment]
<i>(related to <a href='https:///agent/tickets/14423'>Zendesk ticket #14423</a>)</i>

**Comment by fr3fou** [comment]
Thank you for the incredibly fast fix!
