### ISSUE TITLE
`"server_key is not a valid"`after updating to latest verion when calling `client.UpdateAppSettings`

### ISSUE THREAD

**Issue by fr3fou** [GetStream/stream-chat-go#136]
I recently updated to the latest version `v3.12.1` (previously it seems that i was using `v1.0.0`, I didn't pay attention (or it was missing) to the README which shows both an import to `/v3` and an installation step with `/v3` at the end.
Here's my code right now -
```go
	streamChatClient, err := streamchat.NewClient(streamKey, streamSecret)
	if err != nil {
		return nil, nil, err
	}
	streamChatClient.BaseURL = "https://chat-proxy-dublin.stream-io-api.com"
	err := streamChatClient.UpdateAppSettings(&streamchat.AppSettings{
		FirebaseConfig: &streamchat.FirebaseConfig{
			Enabled: true,
			DataTemplate: `{
    "sender": "{{ sender.id }}",
    "dm_id": "{{ channel.id }}",
    "message": "{{ message.id }}"
}`,
			NotificationTemplate: `{
	"title": "{{ sender.nickname }}",
	"body": "{{ message.text }}",
	"sound": "default"
}`,
		},
	})
```

but upon starting that code I get the following error - 
```go
chat-client: HTTP PATCH https://chat-proxy-dublin.stream-io-api.com/app?api_key=<snip> status 400 Bad Request: {"code":4,"message":"UpdateApp failed with error: \"server_key is not a valid\"","StatusCode":400,"duration":"0.00ms","more_info":"https://getstream.io/chat/docs/api_errors_response"}
```
What were some changes from v1 to v3 that could be causing this issue?

**Comment by driver-devel** [comment]
You should provide your server key if firebase is enabled. It could be found in firebase console project settings / cloud messaging section. 

```go
type FirebaseConfig struct {
	Enabled              bool   `json:"enabled"`
        // New field is already there
	ServerKey            string `json:"server_key"`
	NotificationTemplate string `json:"notification_template,omitempty"`
	DataTemplate         string `json:"data_template,omitempty"`
}
```

**Comment by fr3fou** [comment]
> You should provide your server key if firebase is enabled. It could be found in firebase console project settings / cloud messaging section.
> 
> ```go
> type FirebaseConfig struct {
> 	Enabled              bool   `json:"enabled"`
>         // New field is already there
> 	ServerKey            string `json:"server_key"`
> 	NotificationTemplate string `json:"notification_template,omitempty"`
> 	DataTemplate         string `json:"data_template,omitempty"`
> }
> ```

Thank you!
