### ISSUE TITLE
What is the default region?

### ISSUE THREAD

**Issue by tpoxa** [GetStream/stream-chat-go#150]
And how I can define a preferable region? 

Thanks.

**Comment by yaziine** [comment]
The default URL is https://chat.stream-io-api.com which will redirect you to the closest region (cf [this link](https://getstream.io/blog/chat-edge-infrastructure/) for more details).

Can I know why do you need to override this value?

**Comment by tpoxa** [comment]
We had issues with the performance of our backend. Just checking all external services possible connectivity problems. We are based in eu-west-1.

**Comment by yaziine** [comment]
Github Issues are more for bug or request features, since you are facing performance issues it's better to email our support team (support@getstream.io) with a detailed explanation of what you are facing, don't forget to include your app id. 

We will follow up and help you there.

**Comment by tpoxa** [comment]
I think chat API  likewise stream API, should support explicit regions for endpoints (same for endpoints). Because we do use it from a server-side and we do not move our server location a lot :)

**Comment by ferhatelmas** [comment]
It's not needed at all. Edge system will do the best for you.

Actually, Feed infra might adapt to chat eventually
