### ISSUE TITLE
Custom error for duplicate username

### ISSUE THREAD

**Issue by fabriziomoscon** [GetStream/stream-chat-go#165]
We are seeing errors when trying to create new users with a username that is already present in the team. This is expected behaviour. However, if the library could expose custom errors we could check with `errors.As()` that the error is a `ErrDuplicateUsername` and try adding a `1` suffix (and 2, 3... until the http response is 200).
https://getstream.io/chat/docs/react/api_errors_response/

**Comment by yaziine** [comment]
Thank you for raising this, I agree that this could be a good improvement. We will try to prioritize this work. 

In the meantime, I suggest you to cast the error into our `Error` type and check the status code and even the code for more confidence:
```go
_, err = client.UpsertUsers(...)
if err != nil {
	if e, ok := err.(stream.Error); ok {
		if e.StatusCode == http.StatusBadRequest && e.Code == 6 {
			// retry with a different name
		}
	}
}
```

**Comment by peterdeme** [comment]
In my opinion implementing custom error handling in this specific SDK would be too much of a big overhead right now and requires a maintenance that's just too inconvenient for the small team currently. At least until we can't generate code.

Let's just follow Yassine's recommendation for now.
