### ISSUE TITLE
Channel Query function does not expose options

### ISSUE THREAD

**Issue by kimmom** [GetStream/stream-chat-go#183]
[Stream docs Go example](https://getstream.io/chat/docs/go-golang/channel_pagination/?language=go) uses function ch.query which is not exposed. So the example does not work.

```go
options := map[string]interface{}{ 
	"messages": map[string]interface{}{"limit": 50, "id_lt": lastMessageId}, 
	"members":  map[string]interface{}{"limit": 10, "offset": 0}, 
	"watchers": map[string]interface{}{"limit": 20, "offset": 0}, 
} 
 
ch.query(ctx, options, nil)
```

Changing the function to exposed ch.Query doesn't work either since that function does not allow passing options to it.

Thus I found no way to query channel messages with pagination using the Go client.

**Comment by ferhatelmas** [comment]
Yes, it makes sense to export it and we will do it and update the docs accordingly

cc @peterdeme

**Comment by peterdeme** [comment]
Fix in https://github.com/GetStream/stream-chat-go/pull/184

**Comment by ferhatelmas** [comment]
https://github.com/GetStream/stream-chat-go/releases/tag/v5.1.0
