### ISSUE TITLE
Getting timeouts and context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by sw360cab** [GetStream/stream-chat-go#209]
This issue was originally reported on [stream-go2](https://github.com/GetStream/stream-go2/issues/110)

There I found a suggestion to add a ["client" timeout](https://github.com/GetStream/stream-go2/issues/110#issuecomment-878214985)

Is there a similar way to address the issue in the `stream-chat-go` library ?

**Comment by sw360cab** [comment]
The test here

https://github.com/GetStream/stream-chat-go/blob/86a4834eacdf23682b12fd59609658fbe020545f/http_test.go#L48

is using a `context with timeout` to handle something like a client timeout

**Comment by peterdeme** [comment]
Added new constructor and updated docs here: https://github.com/GetStream/stream-chat-go/pull/210
