### ISSUE TITLE
Make auto release on tag publish

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-chat-go#48]
also might want to generate a message such as PRs merged from the previous release.

**Comment by erbesharat** [comment]
I can help with this issue and put together a Github actions workflow to create releases.

This is my suggestion for the release body template but I can just add a simple list for history if it's too much:
```
_2020-01-01_

- [Changelog since v0.0.1](#changes-since-v001)
- [Documentation for v0.0.2](#documentation-for-v002-beta)

## Documentation for v0.0.2

[Documentation](https://example.com/docs)

[Examples](https://example.com/examples)

## Changes since v0.0.1

- Foo bar baz
- Baz bar foo
```

**Comment by ferhatelmas** [comment]
@erbesharat this sounds great, please go ahead!

**Comment by ferhatelmas** [comment]
@peterdeme good one on tag

**Comment by ferhatelmas** [comment]
closing since we have a common flow now.
