### ISSUE TITLE
No matching versions for v2 when fetching package with go get

### ISSUE THREAD

**Issue by ayoisaiah** [GetStream/stream-chat-go#53]
This is the error I get when I try to run the command specified in the README.

![image](https://user-images.githubusercontent.com/13372163/75066624-7aa67b00-54eb-11ea-9422-3c6e9ddfcaa6.png)

**Comment by ferhatelmas** [comment]
@ayoisaiah thanks for catching, updated readme.

Additionally you can use add version as following:

```sh
go get github.com/GetStream/stream-chat-go/v2@v2.1.0
```
