### ISSUE TITLE
Package name inconsistencies create issues on Windows

### ISSUE THREAD

**Issue by lukef** [GetStream/stream-chat-go#61]
`go: 1.13.6`
`os: windows`

Windows treats `GetStream` and `getstream` as the same thing. When vendoring the library on windows and deploying to linux-based systems (i.e. via a Google Cloud function), the vendoring process will use `github.com/GetStream` for all packages.

However, there is a dependency on `github.com/getstream/easyjson` (which uses the lowercase convention) and the build tools will fail to find the vendored dependency when interacting with case-sensitive file systems / OSes.

It would be great if the package names were consistent to avoid this issue.

**Comment by tbarbugli** [comment]
@lukef thank you for reporting this, I am surprised we did not have this problem yet (this library is used on both Linux and OSX). Nevertheless `github.com/getstream/easyjson` is indeed wrong, it only works thanks to some Github magic and it should be changed into `github.com/GetStream/easyjson`

**Comment by keyneston** [comment]
Good find. I should have this sorted today, although it is a bit of a rabbit hole of multiple levels of the package being incorrectly capitalized.
