### ISSUE TITLE
CreateToken does not accept nil value for expiration

### ISSUE THREAD

**Issue by lukef** [GetStream/stream-chat-go#68]
The `CreateToken` function should accept `nil` as a value for token expiration. The `expire` value is a `time.Time` type and it cannot be set to nil.

Also, the documentation on the site it wrong. It shows: `token := client.CreateToken("john", null)` which is a copy error as `null` isn't valid Go code.

**Comment by ferhatelmas** [comment]
@lukef zero time is fine, and it will be treated as nil (no expire). For backward compatibility, better to keep it as now.

Regarding doc, you're right. Updated. Thanks for catching.
