### ISSUE TITLE
[BUG] QueryChannel pagination limit incorrect implementation

### ISSUE THREAD

**Issue by dv-bv** [GetStream/stream-chat-go#74]
Hi people

According to the source code, pagination parameters for the channel querying should be passed within the `filter_conditions`. 
In docs it is suggested to pass the query parameters on the root level of the payload JSON structure (`queryChannelRequest` struct in Go SDK instead of `QueryOption` nested struct).

**References**
In Go SDK:
https://github.com/GetStream/stream-chat-go/blob/master/query.go#L102

In docs:
https://getstream.io/chat/docs/query_channels/#query-options

**Steps to reproduce**
1. Create at least two channels
2. Call `QueryChannels` method without any pagination options passed
3. Make sure you receive your channels in the response
4. Call `QueryChannels` method with explicit pagination rules (limit: 10, offset: 1)

_Expected_
Channels are returned respecting the provided pagination parameters

_Actual_
Empty channels list is returned

**Comment by keyneston** [comment]
Hi @dv-bv this should be fixed in the latest version v2.2.2 can you please confirm?
