### ISSUE TITLE
VerifyWebhook seems to not work

### ISSUE THREAD

**Issue by lukef** [GetStream/stream-chat-go#79]
Using the following code:

```
body, bodyErr := ioutil.ReadAll(request.Body)
if bodyErr != nil {
  ...
}
isValid := streamClient.VerifyWebhook(body, []byte(signature))
```

The value for `isValid` will always be `false`.

I noticed that the hmac used to validate is len 32 and the signature is len 64. Not sure if that's the issue. It's possible i'm also just doing it wrong.

**Comment by ferhatelmas** [comment]
@lukef grab https://github.com/GetStream/stream-chat-go/releases/tag/v2.2.3 please
