### ISSUE TITLE
Drop client/channel interfaces

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-chat-go#97]
Linked to Zendesk issue 

gz#6218

These interfaces should be defined by user and adds no benefit in SDK except maintenance burden.
Additionally, there are too big.

**Comment by shodgetts** [comment]
Agent comment from ferhat elmas in <a href='https://getstream.zendesk.com/agent/tickets/6218'>Zendesk ticket #6218</a>:<br><br>Releasing
